name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if S3 bucket exists and create if not
        run: |
          if ! aws s3api head-bucket --bucket rafaelsdias.dev 2>/dev/null; then
            echo "Bucket does not exist. Creating..."
            aws s3api create-bucket --bucket rafaelsdias.dev --region us-east-1
          else
            echo "Bucket exists."
          fi

      - name: Copy index.html to deploy directory
        run: mkdir -p build && cp index.html build/

      - name: Deploy to AWS
        run: aws s3 sync build/ s3://rafaelsdias.dev --delete