name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Create S3 bucket if it does not exist
        run: |
          aws s3api head-bucket --bucket rafaelsdias.dev || aws s3api create-bucket --bucket rafaelsdias.dev --region us-east-1

      - name: Copy index.html to deploy directory
        run: mkdir -p build && cp index.html build/

      - name: Deploy to AWS
        run: aws s3 sync build/ s3://rafaelsdias.dev --delete